### ISSUE TITLE
能同时支持usb键鼠吗

### ISSUE THREAD

**Issue by vowers** [chrisniael/kbd-usb2ps2#9]
我也不知道哪个环节除了问题，用另一个项目中usb2ps2鼠标的，就是模拟不了，只是识别出鼠标了，大神能改造一下让他同时支持键鼠吗

**Comment by chrisniael** [comment]
Arduino Uno Rev3 内存（2kb）可能装不下这 2 个程序的功能，目前 kbd-usb2ps2 启动后就占用了 Arudino Uno Rev3 约 80% 的内存。
